Repository eclipse-dataspacetck/dsp-tck, pull requests merged in 2024-11, with the labels that each got.

#107 feat: Configurable HTTP Authorization header
  DEPENDENCIES
  config/tck/sample.tck.properties
  dsp/dsp-api/src/main/java/org/eclipse/dataspacetck/dsp/system/api/http/HttpFunctions.java
  dsp/dsp-system/src/main/java/org/eclipse/dataspacetck/dsp/system/DspSystemLauncher.java
Labels: enhancement

#108 feat: Add TestSequenceDiagram annotation
  core/src/main/java/org/eclipse/dataspacetck/core/api/system/TestSequenceDiagram.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationConsumer01Test.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationProvider01Test.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationProvider02Test.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationProvider03Test.java
Labels: documentation, enhancement

#109 feat: implement TestPlan generator AnnotationProcessor
  README.md
  api/core-api/src/main/java/org/eclipse/dataspacetck/api/system/MandatoryTest.java
  api/core-api/src/main/java/org/eclipse/dataspacetck/api/system/TestSequenceDiagram.java
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/java/org/eclipse/dataspacetck/gradle/tasks/GenerateTestPlanTask.java
  core/src/main/java/org/eclipse/dataspacetck/core/api/pipeline/AbstractAsyncPipeline.java
  dsp/dsp-contract-negotiation/build.gradle.kts
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationConsumer01Test.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationProvider01Test.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationProvider02Test.java
  dsp/dsp-contract-negotiation/src/main/java/org/eclipse/dataspacetck/dsp/verification/cn/ContractNegotiationProvider03Test.java
  gradle/libs.versions.toml
  settings.gradle.kts
  tools/build.gradle.kts
  tools/src/main/java/org/eclipse/dataspacetck/annotation/processors/TestPlanGenerator.java
  tools/src/main/java/org/eclipse/dataspacetck/document/model/Category.java
  tools/src/main/java/org/eclipse/dataspacetck/document/model/TestCase.java
  tools/src/main/java/org/eclipse/dataspacetck/document/model/TestGraph.java
  tools/src/main/java/org/eclipse/dataspacetck/document/model/TestSuite.java
  tools/src/main/java/org/eclipse/dataspacetck/rendering/markdown/MarkdownRenderer.java
  tools/src/main/java/org/eclipse/dataspacetck/rendering/mermaid/MermaidRenderer.java
  tools/src/main/java/org/eclipse/dataspacetck/rendering/plantuml/PlantumlRenderer.java
  tools/src/main/java/org/eclipse/dataspacetck/rendering/spi/DiagramImageRenderer.java
  tools/src/main/java/org/eclipse/dataspacetck/rendering/spi/TestPlanRenderer.java
  tools/src/main/resources/META-INF/gradle/incremental.annotation.processors
  tools/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  tools/src/test/java/org/eclipse/dataspacetck/document/TestPlanRendererImplTest.java
  tools/src/test/java/org/eclipse/dataspacetck/document/model/CategoryTest.java
  tools/src/test/java/org/eclipse/dataspacetck/document/model/TestGraphTest.java
  tools/src/test/resources/testimage.png
Labels: documentation

#112 feat: use common code from `tck-common` module
  api/core-api/src/main/java/org/eclipse/dataspacetck/api/system/MandatoryTest.java
  api/core-api/src/main/java/org/eclipse/dataspacetck/api/system/TestSequenceDiagram.java
  build.gradle.kts
  dsp/dsp-contract-negotiation/build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  tools/build.gradle.kts
Labels: enhancement
